services:
  web:
    networks:
      - stealthysite
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  
  postgres:
    networks:
      - stealthysite
    image: "postgres:17.5-alpine3.21"
    ports: 
      - "5432:5432"
    env_file:
      - .env
  
  postgres-admin:
    image: dpage/pgadmin4
    networks:
     - stealthysite
    env_file:
      - .env

# networks
networks:
  stealthysite:
    driver: bridge 
  