# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write
  artifact-metadata: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [24.x, 26.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --if-present

      - name: Test frontend
        working-directory: ./frontend
        run: npm test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist ${{ matrix.node-version }}
          path: |
            ./frontend/dist/

      - name: Archive code coverage results
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage-report ${{ matrix.node-version }}
          path: ./frontend/coverage

      - name: Code coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./frontend/coverage/frontend/cobertura-coverage.xml
          badge: true
          format: markdown
          output: both

      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
